# Generated by Django 5.2.9 on 2026-04-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE app_customuser RENAME COLUMN branch TO branch_old;",
            reverse_sql="ALTER TABLE app_customuser RENAME COLUMN branch_old TO branch;",
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.branch'),
        ),
        migrations.RunSQL(
            "UPDATE app_customuser SET branch_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
